name: kindle-env
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py39h2bbff1b_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.2=py39h7cc1a96_1
  - brotli=1.0.9=ha925a31_2
  - ca-certificates=2021.10.8=h5b45459_0
  - certifi=2021.10.8=py39hcbf5309_1
  - cffi=1.15.0=py39h2bbff1b_0
  - click=8.0.3=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py39hd77b12b_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py39haa95532_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - importlib-metadata=4.8.2=py39haa95532_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.4.1=py39haa95532_1
  - ipython=7.29.0=py39hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.0=py39haa95532_1
  - jinja2=3.0.2=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h2bbff1b_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=7.1.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py39haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - kiwisolver=1.3.1=py39hd77b12b_0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.2.0=hd0e1b90_0
  - libwebp=1.2.0=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py39h2bbff1b_0
  - matplotlib=3.5.0=py39haa95532_0
  - matplotlib-base=3.5.0=py39h6214cd6_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h2bbff1b_1000
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=py_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py39haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nltk=3.6.5=pyhd3eb1b0_0
  - notebook=6.4.6=py39haa95532_0
  - numexpr=2.8.1=py39hb80d3ca_0
  - numpy=1.21.2=py39hfca59bb_0
  - numpy-base=1.21.2=py39h0829f74_0
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1l=h8ffe710_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py39h6214cd6_0
  - pandocfilters=1.4.3=py39haa95532_1
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py39hd45dc43_0
  - pip=21.2.4=py39haa95532_0
  - prometheus_client=0.12.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py39hd77b12b_6
  - pyrsistent=0.18.0=py39h196d8e1_0
  - python=3.9.7=h6244533_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd3eb1b0_0
  - pywin32=302=py39h827c3e9_1
  - pywinpty=0.5.7=py39haa95532_0
  - pyzmq=22.3.0=py39hd77b12b_2
  - qt=5.9.7=vc14h73c81de_0
  - regex=2021.8.3=py39h2bbff1b_0
  - scikit-learn=1.0.2=py39hf11a4ad_1
  - scikit-surprise=1.1.1=py39h5d4886f_2
  - scipy=1.7.3=py39h0a974cb_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py39haa95532_0
  - sip=4.19.13=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=h2bbff1b_0
  - terminado=0.9.4=py39haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h2bbff1b_0
  - tornado=6.1=py39h2bbff1b_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39haa95532_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py39haa95532_2
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h8cc25b3_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - altair==4.2.0
    - astor==0.8.1
    - base58==2.1.1
    - blinker==1.4
    - blis==0.7.5
    - cachetools==5.0.0
    - catalogue==1.0.0
    - charset-normalizer==2.0.10
    - cymem==2.0.6
    - en-core-web-sm==2.3.1
    - gensim==3.8.3
    - gitdb==4.0.9
    - gitpython==3.1.26
    - idna==3.3
    - ipywidgets==7.6.5
    - jupyterlab-widgets==1.0.2
    - murmurhash==1.0.6
    - plac==1.1.3
    - plotly==5.5.0
    - preshed==3.0.6
    - protobuf==3.19.3
    - pyarrow==6.0.1
    - pydeck==0.7.1
    - pympler==1.0.1
    - pytz-deprecation-shim==0.1.0.post0
    - requests==2.27.1
    - smart-open==5.2.1
    - smmap==5.0.0
    - spacy==2.3.7
    - srsly==1.0.5
    - streamlit==1.4.0
    - tenacity==8.0.1
    - texthero==1.1.0
    - thinc==7.4.5
    - toml==0.10.2
    - toolz==0.11.2
    - tzdata==2021.5
    - tzlocal==4.1
    - unidecode==1.3.2
    - urllib3==1.26.8
    - validators==0.18.2
    - wasabi==0.9.0
    - watchdog==2.1.6
    - widgetsnbextension==3.5.2
    - wordcloud==1.8.1
